Made generated templates closer to the official quilt templates so th…
Jaffe2718/quilt-template-mod-generator pull request #3
Opened 2023-10-23 23:27 UTC by c-leri

…at it actually works

- Removed the "Use QuiltFlower" checkbox as VineFlower (new version of QuiltFlower) is already available by default
- Removed the "Used QSL & QFAPI" checkbox as the official quilt template doesn't work without qsl
- Removed the QSL version selector as QSL is bundled with QFAPI
- Removed SNAPSHOT versions of QFAPI as it didn't work with the official quilt template

2023-10-24 03:04 UTC, Jaffe2718 requested changes
There are still some problems with the design of this Pull Request, so I can't merge to the master branch for now. I still have some changes to make to the original project, so you may need to refork it to avoid git conflicts.

2023-10-24 03:04 UTC, Jaffe2718 commented on res/static/build.gradle
> +		"example_mod" {
I don't recommend that you write the mod id like this in a static build.gradle, it should be generated in Javascript like I did before, and the mod id should be entered by the user instead of using `example_mod` by default.

2023-10-24 03:04 UTC, Jaffe2718 commented on res/static/.gitignore
> +# Gradle
I don't recommend including the git configuration file inside the user's project, unless we can give the user access to the full VCS project via the .git folder. But it seems that this is difficult to implement and will not be considered for now.

2023-10-24 03:04 UTC, Jaffe2718 commented on res/static/build.gradle
> +jar {
Currently there is no function to add a LICENSE template to the project generated for the user, so we will configure this after this function is realized.

2023-10-24 03:04 UTC, Jaffe2718 commented on res/static/settings.gradle
Need to add SNAPSHOT version of Quilt Maven:
```groovy
maven {
    name = 'Quilt Snapshots',
    url = 'https://maven.quiltmc.org/repository/snapshot'
}
```

2023-10-24 03:04 UTC, Jaffe2718 commented on res/static/.editorconfig
This configuration I don't think is necessary, even if the IDE is different for different users.

2023-10-24 03:04 UTC, Jaffe2718 commented on res/static/.gitattributes
There is no need to force the addition of a git configuration file, if necessary, you can give the user the option to add the full VCS configuration, of course, this feature is more difficult to achieve, do not consider for the time being.

2023-10-24 03:04 UTC, Jaffe2718 commented on js/init_versions.js
Although QFAPI and QSL are bound when the player downloads the module, it is necessary for the developer to manually configure the version of QFAPI and QSL.

2023-10-24 03:04 UTC, Jaffe2718 commented on js/get_version/get_vers.js
SNAPSHOT versions of QSL and QFAPI are still necessary because it is possible for developers to configure SNAPSHOT versions of both QSL and QFAPI while requiring players to download higher versions of the QSL and QFAPI modules.

2023-10-24 03:04 UTC, Jaffe2718 commented on js/core/gen_prj_zip.js
> +    add_static_file_to_folder(zip, ".editorconfig");
Don't add editor configuration files and VCS configuration files to the project.

2023-10-24 03:08 UTC, c-leri commented on res/static/build.gradle
> +		"example_mod" {
Ah yes I did overlook that

2023-10-24 03:10 UTC, c-leri commented on res/static/.gitignore
> +# Gradle
This is the default .gitignore file provided in the official quilt template mod, it allows developers using the template to have a good .gitignore base to build upon

2023-10-24 03:11 UTC, c-leri commented on res/static/build.gradle
> +jar {
There isn't a LICENSE file provided in the official quilt template mod either so this isn't really a problem as developers can just provide their own but it would be nice to add an option to the generator to add a license file directly

2023-10-24 03:12 UTC, c-leri commented on res/static/.editorconfig
This is also included in the official quilt template mod, it provide a way to ensure that all mods have some of the same base code style

2023-10-24 22:57 UTC, c-leri commented on res/static/build.gradle
> +jar {
I added a license selector to the template generator :+1:

2023-10-24 23:06 UTC, c-leri commented on res/static/settings.gradle
Done :+1:

2023-10-25 02:15 UTC, Jaffe2718 requested changes
One last little problem: the java source needs to be added to `package <group_id>. <mod_id>;` statement.

Anyway, this is nice update.

2023-10-25 02:15 UTC, Jaffe2718 commented on js/core/gen_files_content.js
> + */
please add `package <group_id>.<mod_id>;` for this function;

2023-10-25 02:15 UTC, Jaffe2718 commented on js/core/gen_files_content.js
> + */
please add `package <group_id>.<mod_id>;` for this function.

2023-10-25 02:17 UTC, merged

2023-10-25 02:57 UTC, Jaffe2718 commented
I have already add `"license"` field into `quilt.mod.json` generate function, see [83d913f](https://github.com/Jaffe2718/quilt-template-mod-generator/commit/83d913f9ae42752429681bc90e5833f41ae52214)

In the next phase, I will add more types of LICENSE.
Then I will prepare a project template generation compatible with the Kotlin language for writing quilt mods.

Finally, thank you very much for your contribution to this project!

2023-10-25 03:21 UTC, c-leri commented
It was a pleasure! I love the Kotlin template idea!

2023-10-25 11:12 UTC, Jaffe2718 commented
I found a very serious problem with Quilt's official quilt-template-mod project, which is that you can't select the Minecraft version and the QFAPI & QSL versions, see [build.gradle](https://github.com/QuiltMC/quilt-template-mod/blob/1.20.1/build.gradle). So I'll have to abandon the content of this Pull Request and fall back to the previous version. Of course, I'll still keep the master branch up to date, but I'll use the old branch for GitHub Pages for now!

2023-10-25 11:22 UTC, Jaffe2718 commented
the curret pages is base on the read-only branche [old](https://github.com/Jaffe2718/quilt-template-mod-generator/tree/old)

2023-10-25 11:27 UTC, c-leri commented
What do you mean ? The Minecraft and QSL/QFAPI versions are set in the gradle/libs.versions.toml file

2023-10-25 11:28 UTC, Jaffe2718 commented
But Gradle projects use build.gradle and gradle.properties to configure dependencies, and too many configuration files is not a good way to do that.

2023-10-25 11:36 UTC, c-leri commented
I believe that the quilt template mod team decided to do it that way because it is good practice for gradle project

2023-10-25 11:43 UTC, Jaffe2718 commented
Or maybe the master branch stays like this for now, and continues to work on the Kotlin-supported options, and then goes live when the Kotlin update is done. New code temporarily uploaded to dev branch.